<?php require './templates/layouts/header.phtml' ?>

<form method='post' action='login'>
    <div class='form-group'>
        <label for='usuario'>usuario</label>
        <input type='text' class='form-control' name='usuario'>
    </div>
    <div class='form-group>
        <label for= 'password'>Password</label>
        <input type='password' class='form-control' name='password'>
    </div>
    <button type='submit' class='btn btn-primary'>Login</button>
</form>

<?php require './templates/layouts/footer.phtml' ?>