<?php require './templates/layouts/header.phtml' ?>

<?php require './templates/logout.phtml' ?>
<?php require './templates/usuarios_y_libros/lista_libros.phtml' ?>
<?php require './templates/usuarios_y_libros/vermas_libro.phtml' ?>
<?php require './templates/usuarios_y_libros/formulario_libros.phtml' ?>
<?php require './templates/usuarios_y_libros/editar_libros.phtml' ?>
<?php require './templates/usuarios_y_libros/lista_usuarios.phtml' ?>
<?php require './templates/usuarios_y_libros/vermas_usuario.phtml' ?>
<?php require './templates/usuarios_y_libros/formulario_usuarios.phtml' ?>
<?php require './templates/usuarios_y_libros/editar_usuario.phtml' ?>

<?php require './templates/layouts/footer.phtml' ?>