<h1>Editar Libro</h1>

<form action="editar_libro" method="post">
    <input type="number" name="id" placeholder="Ingrese ID">
    <input type="text" name="nombre" placeholder="Ingrese su nombre">
    <input type="text" name="generos" placeholder="Ingrese los generos"> <br>
    <input type="number" name="precio" placeholder="Ingrese el precio"> <br>
    <input type="text" name="id_usuario" placeholder="Ingrese los id de usuarios"> <br>

    <button type="submit">EDITAR</button>
</form>