<h1>Editar usuario</h1>

<form action="editar_usuario" method="post">
    <input type="number" name="id" placeholder="Ingrese ID">
    <input type="text" name="nombre" placeholder="Ingrese su nombre">
    <input type="text" name="apellido" placeholder="Ingrese su apellido"> <br>
    <label for="generos">Elige género</label>
    <select name="generos">
        <option value="hombre">Hombre</option>
        <option value="mujer">Mujer</option>
    </select> <br>
    <button type="submit">EDITAR</button>
</form>