<h1>Agregar usuario</h1>

<form action="agregar_usuario" method="post">
    <input type="text" name="nombre" placeholder="Ingrese su nombre">
    <input type="text" name="apellido" placeholder="Ingrese su apellido"> <br>
    <label for="generos">Elige genero</label>
    <select name="generos">
        <option value="hombre">hombre</option>
        <option value="mujer">mujer</option>
    </select> <br>

        <button type="submit">AGREGAR</button>
</form>

