<h1>Agregar libro </h1>

<form action="agregar_libro" method="post" class="my-4">
    <input type="text" name="nombre" placeholder="Ingrese el nombre">
    <input type="text" name="generos" placeholder="Ingrese los generos"> <br>
    <input type="number" name="precio" placeholder="Ingrese el precio"> <br>
    <input type="text" name="id_usuario" placeholder="Ingrese los id de usuarios"> <br>

    <button type="submit" class="btn btn-primary mt-2">AGREGAR</button>
</form>

