<?php require './templates/usuarios_y_libros/formulario_usuarios.phtml' ?>

<h1>Usuarios</h1>
<ul class="list-group">
    <?php foreach ($usuarios as $usuario): ?>
        <li class="list-group-item item-libro>' 
            <div class ="label">
                <b><?= htmlspecialchars($usuario->Nombre) ?></b>
            </div>
            <div>
            <a href="ver_mas_usuario/<?=$usuario->id_usuario?>">Ver más</a> .
            </div>
            <div>
                <a href="eliminar_usuario/<?=$usuario->id_usuario?>">Borrar</a>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<?php
    if (isset($count2)){
        echo '<p class="mt-3"><small> mostrando ' . $count2 . ' usuarios </small></p>';
    }
?>

<?php require './templates/usuarios_y_libros/editar_usuario.phtml' ?>
<?php require 'templates/layouts/footer.phtml' ?>